In [58]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest

In [2]:
df = pd.read_csv('./data/modified.csv')

C:\Users\castr\AppData\Local\Temp\ipykernel_21284\1569098086.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/modified.csv')

In [3]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25993 entries, 0 to 25992
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  25993 non-null  int64
 1   event_id                    25993 non-null  int64
 2   process_name                24008 non-null  object
 3   hostname                    25993 non-null  object
 4   hostname_role               25993 non-null  object
 5   event_type                  25993 non-null  object
 6   hour_of_day                 25993 non-null  int64
 7   day_of_week                 25993 non-null  object
 8   user_context                2517 non-null   object
 9   is_admin_process            25993 non-null  int64
 10  dest_port                   25993 non-null  int64
 11  source_ip_type              25993 non-null  object
 12  dest_ip_type                25993 non-null  object
 13  user_id                     2462 non-null   object
 14  process_path_risk_score     25993 non-null  float64
 15  command_line_risk_keywords  25993 non-null  int64
 16  parent_process_name         24 non-null     object
 17  file_extension_risk         25993 non-null  int64
 18  logon_type                  136 non-null    float64
 19  registry_path_type          25993 non-null  object
 20  is_sensitive_privilege      25993 non-null  int64
 21  event_count_1h              1948 non-null   float64
 22  unique_destinations_1h      25993 non-null  int64
 23  source_port                 452 non-null    float64
 24  protocol                    452 non-null    object
 25  is_outbound                 25993 non-null  int64
 26  source_address              326 non-null    object
 27  dest_address                197 non-null    object
 28  process_path                21710 non-null  object
 29  parent_process_path         24 non-null     object
 30  command_line                48 non-null     object
 31  file_path                   835 non-null    object
 32  file_name                   835 non-null    object
 33  file_extension              629 non-null    object
dtypes: float64(4), int64(10), object(20)
memory usage: 6.7+ MB

In [4]:
df = df.dropna(subset=['process_name'])
df['user_context'] = df['user_context'].fillna('SYSTEM')
df['user_id'] = df['user_id'].fillna('unknown')
df['parent_process_name'] = df['parent_process_name'].fillna('unknown')
df['parent_process_path'] = df['parent_process_path'].fillna('unknown')
df['logon_type'] = df['logon_type'].fillna(0)
df['event_count_1h'] = df['event_count_1h'].fillna(0)
df['source_port'] = df['source_port'].fillna(0)
df['protocol'] = df['protocol'].fillna('none')
df['source_address'] = df['source_address'].fillna('none')
df['dest_address'] = df['dest_address'].fillna('none')
df['process_path'] = df['process_path'].fillna('unknown')
df['command_line'] = df['command_line'].fillna('none')
df['file_path'] = df['file_path'].fillna('none')
df['file_name'] = df['file_name'].fillna('none')
df['file_extension'] = df['file_extension'].fillna('none')

In [6]:
df.head()

,Unnamed: 0,event_id,process_name,hostname,hostname_role,event_type,hour_of_day,day_of_week,user_context,is_admin_process,...,protocol,is_outbound,source_address,dest_address,process_path,parent_process_path,command_line,file_path,file_name,file_extension
0,0,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,SYSTEM,0,...,6,0,::1,::1,unknown,unknown,none,none,none,none
1,1,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,SYSTEM,0,...,6,0,::1,::1,unknown,unknown,none,none,none,none
2,2,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,SYSTEM,0,...,6,0,::1,::1,unknown,unknown,none,none,none,none
3,3,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,SYSTEM,0,...,6,0,::1,::1,unknown,unknown,none,none,none,none
4,4,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,SYSTEM,0,...,6,0,::1,::1,unknown,unknown,none,none,none,none

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24008 entries, 0 to 25992
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  24008 non-null  int64
 1   event_id                    24008 non-null  int64
 2   process_name                24008 non-null  object
 3   hostname                    24008 non-null  object
 4   hostname_role               24008 non-null  object
 5   event_type                  24008 non-null  object
 6   hour_of_day                 24008 non-null  int64
 7   day_of_week                 24008 non-null  object
 8   user_context                24008 non-null  object
 9   is_admin_process            24008 non-null  int64
 10  dest_port                   24008 non-null  int64
 11  source_ip_type              24008 non-null  object
 12  dest_ip_type                24008 non-null  object
 13  user_id                     24008 non-null  object
 14  process_path_risk_score     24008 non-null  float64
 15  command_line_risk_keywords  24008 non-null  int64
 16  parent_process_name         24008 non-null  object
 17  file_extension_risk         24008 non-null  int64
 18  logon_type                  24008 non-null  float64
 19  registry_path_type          24008 non-null  object
 20  is_sensitive_privilege      24008 non-null  int64
 21  event_count_1h              24008 non-null  float64
 22  unique_destinations_1h      24008 non-null  int64
 23  source_port                 24008 non-null  float64
 24  protocol                    24008 non-null  object
 25  is_outbound                 24008 non-null  int64
 26  source_address              24008 non-null  object
 27  dest_address                24008 non-null  object
 28  process_path                24008 non-null  object
 29  parent_process_path         24008 non-null  object
 30  command_line                24008 non-null  object
 31  file_path                   24008 non-null  object
 32  file_name                   24008 non-null  object
 33  file_extension              24008 non-null  object
dtypes: float64(4), int64(10), object(20)
memory usage: 6.4+ MB

In [8]:
df.to_csv('./data/new.csv')

In [ ]:
df.drop(columns=['day_of_week'],inplace=True)

In [11]:
df.drop(columns=['parent_process_name','parent_process_path','command_line','source_address','dest_address','user_id','user_context','logon_type','source_port','protocol'],inplace=True)

In [13]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24008 entries, 0 to 25992
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   event_id                    24008 non-null  int64
 1   process_name                24008 non-null  object
 2   hostname                    24008 non-null  object
 3   hostname_role               24008 non-null  int64
 4   event_type                  24008 non-null  object
 5   hour_of_day                 24008 non-null  int64
 6   is_admin_process            24008 non-null  int64
 7   dest_port                   24008 non-null  int64
 8   source_ip_type              24008 non-null  int64
 9   dest_ip_type                24008 non-null  int64
 10  process_path_risk_score     24008 non-null  float64
 11  command_line_risk_keywords  24008 non-null  int64
 12  file_extension_risk         24008 non-null  int64
 13  registry_path_type          24008 non-null  int64
 14  is_sensitive_privilege      24008 non-null  int64
 15  event_count_1h              24008 non-null  float64
 16  unique_destinations_1h      24008 non-null  int64
 17  is_outbound                 24008 non-null  int64
 18  process_path                24008 non-null  object
 19  file_path                   24008 non-null  object
 20  file_name                   24008 non-null  object
 21  file_extension              24008 non-null  object
dtypes: float64(2), int64(13), object(7)
memory usage: 4.2+ MB

In [18]:
le = LabelEncoder()
for col in ['source_ip_type', 'dest_ip_type', 'registry_path_type', 'hostname_role']:
    df[col] = le.fit_transform(df[col])

In [21]:
df = pd.get_dummies(df, columns=['event_type'])
freq = df['process_name'].value_counts(normalize=True)
df['process_name_freq'] = df['process_name'].map(freq)

In [22]:
def bin_port(port):
    if port <= 1023: return 'well_known'
    elif port <= 49151: return 'registered'
    else: return 'dynamic'

df['dest_port_category'] = df['dest_port'].apply(bin_port)
df = pd.get_dummies(df, columns=['dest_port_category'])

In [23]:
risky_dirs = ['temp', 'downloads', 'appdata', 'public', 'desktop']
df['process_in_risky_dir'] = df['process_path'].str.lower().str.contains('|'.join(risky_dirs), na=False).astype(int)

In [25]:
df.head()

,event_id,process_name,hostname,hostname_role,hour_of_day,is_admin_process,dest_port,source_ip_type,dest_ip_type,process_path_risk_score,...,event_type_CreatePipe,event_type_DeleteKey,event_type_DeleteValue,event_type_INFO,event_type_SetValue,process_name_freq,dest_port_category_dynamic,dest_port_category_registered,dest_port_category_well_known,process_in_risky_dir
0,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,0,8,0,389,0,1,0.5,...,False,False,False,False,False,0.004957,False,False,True,0
1,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,0,8,0,389,0,1,0.5,...,False,False,False,False,False,0.000083,False,False,True,0
2,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,0,8,0,389,0,1,0.5,...,False,False,False,False,False,0.004957,False,False,True,0
3,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,0,8,0,389,0,1,0.5,...,False,False,False,False,False,0.004957,False,False,True,0
4,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,0,8,0,389,0,1,0.5,...,False,False,False,False,False,0.000083,False,False,True,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24008 entries, 0 to 25992
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   event_id                       24008 non-null  int64
 1   process_name                   24008 non-null  object
 2   hostname                       24008 non-null  object
 3   hostname_role                  24008 non-null  int64
 4   hour_of_day                    24008 non-null  int64
 5   is_admin_process               24008 non-null  int64
 6   dest_port                      24008 non-null  int64
 7   source_ip_type                 24008 non-null  int64
 8   dest_ip_type                   24008 non-null  int64
 9   process_path_risk_score        24008 non-null  float64
 10  command_line_risk_keywords     24008 non-null  int64
 11  file_extension_risk            24008 non-null  int64
 12  registry_path_type             24008 non-null  int64
 13  is_sensitive_privilege         24008 non-null  int64
 14  event_count_1h                 24008 non-null  float64
 15  unique_destinations_1h         24008 non-null  int64
 16  is_outbound                    24008 non-null  int64
 17  process_path                   24008 non-null  object
 18  file_path                      24008 non-null  object
 19  file_name                      24008 non-null  object
 20  file_extension                 24008 non-null  object
 21  event_type_AUDIT_FAILURE       24008 non-null  bool
 22  event_type_AUDIT_SUCCESS       24008 non-null  bool
 23  event_type_ConnectPipe         24008 non-null  bool
 24  event_type_CreateKey           24008 non-null  bool
 25  event_type_CreatePipe          24008 non-null  bool
 26  event_type_DeleteKey           24008 non-null  bool
 27  event_type_DeleteValue         24008 non-null  bool
 28  event_type_INFO                24008 non-null  bool
 29  event_type_SetValue            24008 non-null  bool
 30  process_name_freq              24008 non-null  float64
 31  dest_port_category_dynamic     24008 non-null  bool
 32  dest_port_category_registered  24008 non-null  bool
 33  dest_port_category_well_known  24008 non-null  bool
 34  process_in_risky_dir           24008 non-null  int64
dtypes: bool(12), float64(3), int64(14), object(6)
memory usage: 4.7+ MB

In [27]:
risky_dirs = ['temp', 'downloads', 'appdata', 'public', 'desktop']
df['file_in_risky_dir'] = df['file_path'].str.lower().str.contains('|'.join(risky_dirs), na=False).astype(int)

df['is_executable'] = df['file_name'].str.lower().str.endswith(('.exe', '.bat', '.ps1', '.vbs', '.cmd'), na=False).astype(int)

df.drop(columns=['process_name', 'hostname', 'process_path', 'file_path', 'file_name', 'file_extension'], inplace=True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24008 entries, 0 to 25992
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   event_id                       24008 non-null  int64
 1   hostname_role                  24008 non-null  int64
 2   hour_of_day                    24008 non-null  int64
 3   is_admin_process               24008 non-null  int64
 4   dest_port                      24008 non-null  int64
 5   source_ip_type                 24008 non-null  int64
 6   dest_ip_type                   24008 non-null  int64
 7   process_path_risk_score        24008 non-null  float64
 8   command_line_risk_keywords     24008 non-null  int64
 9   file_extension_risk            24008 non-null  int64
 10  registry_path_type             24008 non-null  int64
 11  is_sensitive_privilege         24008 non-null  int64
 12  event_count_1h                 24008 non-null  float64
 13  unique_destinations_1h         24008 non-null  int64
 14  is_outbound                    24008 non-null  int64
 15  event_type_AUDIT_FAILURE       24008 non-null  bool
 16  event_type_AUDIT_SUCCESS       24008 non-null  bool
 17  event_type_ConnectPipe         24008 non-null  bool
 18  event_type_CreateKey           24008 non-null  bool
 19  event_type_CreatePipe          24008 non-null  bool
 20  event_type_DeleteKey           24008 non-null  bool
 21  event_type_DeleteValue         24008 non-null  bool
 22  event_type_INFO                24008 non-null  bool
 23  event_type_SetValue            24008 non-null  bool
 24  process_name_freq              24008 non-null  float64
 25  dest_port_category_dynamic     24008 non-null  bool
 26  dest_port_category_registered  24008 non-null  bool
 27  dest_port_category_well_known  24008 non-null  bool
 28  process_in_risky_dir           24008 non-null  int64
 29  file_in_risky_dir              24008 non-null  int64
 30  is_executable                  24008 non-null  int64
dtypes: bool(12), float64(3), int64(16)
memory usage: 3.9 MB

In [29]:
df.head()

,event_id,hostname_role,hour_of_day,is_admin_process,dest_port,source_ip_type,dest_ip_type,process_path_risk_score,command_line_risk_keywords,file_extension_risk,...,event_type_DeleteValue,event_type_INFO,event_type_SetValue,process_name_freq,dest_port_category_dynamic,dest_port_category_registered,dest_port_category_well_known,process_in_risky_dir,file_in_risky_dir,is_executable
0,5156,0,8,0,389,0,1,0.5,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
1,5156,0,8,0,389,0,1,0.5,0,0,...,False,False,False,0.000083,False,False,True,0,0,0
2,5156,0,8,0,389,0,1,0.5,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
3,5156,0,8,0,389,0,1,0.5,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
4,5156,0,8,0,389,0,1,0.5,0,0,...,False,False,False,0.000083,False,False,True,0,0,0

In [ ]:
df.drop(columns=['hour_of_day', 'unique_destinations_1h', 'dest_port'], inplace=True)

In [35]:
for i in df.columns:
    print(f"{i}: {len(df[i].unique())}")

event_id: 26
hostname_role: 2
hour_of_day: 1
is_admin_process: 2
dest_port: 13
source_ip_type: 3
dest_ip_type: 4
process_path_risk_score: 3
command_line_risk_keywords: 2
file_extension_risk: 2
registry_path_type: 2
is_sensitive_privilege: 2
event_count_1h: 530
unique_destinations_1h: 1
is_outbound: 2
event_type_AUDIT_FAILURE: 2
event_type_AUDIT_SUCCESS: 2
event_type_ConnectPipe: 2
event_type_CreateKey: 2
event_type_CreatePipe: 2
event_type_DeleteKey: 2
event_type_DeleteValue: 2
event_type_INFO: 2
event_type_SetValue: 2
process_name_freq: 34
dest_port_category_dynamic: 2
dest_port_category_registered: 2
dest_port_category_well_known: 2
process_in_risky_dir: 2
file_in_risky_dir: 2
is_executable: 2

In [37]:
df['event_count_1h'] = pd.cut(df['event_count_1h'],
                               bins=[0, 10, 50, 100, float('inf')],
                               labels=[0, 1, 2, 3],
                               include_lowest=True).astype(int)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24008 entries, 0 to 25992
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   event_id                       24008 non-null  int64
 1   hostname_role                  24008 non-null  int64
 2   is_admin_process               24008 non-null  int64
 3   source_ip_type                 24008 non-null  int64
 4   dest_ip_type                   24008 non-null  int64
 5   process_path_risk_score        24008 non-null  float64
 6   command_line_risk_keywords     24008 non-null  int64
 7   file_extension_risk            24008 non-null  int64
 8   registry_path_type             24008 non-null  int64
 9   is_sensitive_privilege         24008 non-null  int64
 10  event_count_1h                 24008 non-null  int64
 11  is_outbound                    24008 non-null  int64
 12  event_type_AUDIT_FAILURE       24008 non-null  bool
 13  event_type_AUDIT_SUCCESS       24008 non-null  bool
 14  event_type_ConnectPipe         24008 non-null  bool
 15  event_type_CreateKey           24008 non-null  bool
 16  event_type_CreatePipe          24008 non-null  bool
 17  event_type_DeleteKey           24008 non-null  bool
 18  event_type_DeleteValue         24008 non-null  bool
 19  event_type_INFO                24008 non-null  bool
 20  event_type_SetValue            24008 non-null  bool
 21  process_name_freq              24008 non-null  float64
 22  dest_port_category_dynamic     24008 non-null  bool
 23  dest_port_category_registered  24008 non-null  bool
 24  dest_port_category_well_known  24008 non-null  bool
 25  process_in_risky_dir           24008 non-null  int64
 26  file_in_risky_dir              24008 non-null  int64
 27  is_executable                  24008 non-null  int64
dtypes: bool(12), float64(2), int64(14)
memory usage: 3.4 MB

In [40]:
df.head()

,event_id,hostname_role,is_admin_process,source_ip_type,dest_ip_type,process_path_risk_score,command_line_risk_keywords,file_extension_risk,registry_path_type,is_sensitive_privilege,...,event_type_DeleteValue,event_type_INFO,event_type_SetValue,process_name_freq,dest_port_category_dynamic,dest_port_category_registered,dest_port_category_well_known,process_in_risky_dir,file_in_risky_dir,is_executable
0,5156,0,0,0,1,0.5,0,0,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
1,5156,0,0,0,1,0.5,0,0,0,0,...,False,False,False,0.000083,False,False,True,0,0,0
2,5156,0,0,0,1,0.5,0,0,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
3,5156,0,0,0,1,0.5,0,0,0,0,...,False,False,False,0.004957,False,False,True,0,0,0
4,5156,0,0,0,1,0.5,0,0,0,0,...,False,False,False,0.000083,False,False,True,0,0,0

In [41]:
df = df.sample(frac=1).reset_index(drop=True)

In [50]:
df.head()

,event_id,hostname_role,is_admin_process,source_ip_type,dest_ip_type,process_path_risk_score,command_line_risk_keywords,file_extension_risk,registry_path_type,is_sensitive_privilege,...,event_type_DeleteValue,event_type_INFO,event_type_SetValue,process_name_freq,dest_port_category_dynamic,dest_port_category_registered,dest_port_category_well_known,process_in_risky_dir,file_in_risky_dir,is_executable
0,12,0,0,2,3,0.1,0,0,0,0,...,False,False,False,0.577266,0,0,1,0,0,0
1,4658,0,0,2,3,0.5,0,0,0,0,...,False,False,False,0.030407,0,0,1,0,0,0
2,12,0,0,2,3,0.1,0,0,0,0,...,False,False,False,0.577266,0,0,1,0,0,0
3,12,0,0,2,3,0.1,0,0,0,0,...,False,False,False,0.577266,0,0,1,0,0,0
4,12,0,0,2,3,0.1,0,0,0,0,...,False,False,False,0.577266,0,0,1,0,0,0

In [47]:
df['dest_port_category_registered'] = df['dest_port_category_registered'].astype('int')

In [49]:
df['dest_port_category_dynamic'] = df['dest_port_category_dynamic'].astype('int')
df['dest_port_category_well_known'] = df['dest_port_category_well_known'].astype('int')

In [51]:
df['event_type_DeleteValue'] = df['event_type_DeleteValue'].astype('int')
df['event_type_INFO'] = df['event_type_INFO'].astype('int')
df['event_type_SetValue'] = df['event_type_SetValue'].astype('int')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24008 entries, 0 to 24007
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   event_id                       24008 non-null  int64
 1   hostname_role                  24008 non-null  int64
 2   is_admin_process               24008 non-null  int64
 3   source_ip_type                 24008 non-null  int64
 4   dest_ip_type                   24008 non-null  int64
 5   process_path_risk_score        24008 non-null  float64
 6   command_line_risk_keywords     24008 non-null  int64
 7   file_extension_risk            24008 non-null  int64
 8   registry_path_type             24008 non-null  int64
 9   is_sensitive_privilege         24008 non-null  int64
 10  event_count_1h                 24008 non-null  int64
 11  is_outbound                    24008 non-null  int64
 12  event_type_AUDIT_FAILURE       24008 non-null  bool
 13  event_type_AUDIT_SUCCESS       24008 non-null  bool
 14  event_type_ConnectPipe         24008 non-null  bool
 15  event_type_CreateKey           24008 non-null  bool
 16  event_type_CreatePipe          24008 non-null  bool
 17  event_type_DeleteKey           24008 non-null  bool
 18  event_type_DeleteValue         24008 non-null  int64
 19  event_type_INFO                24008 non-null  int64
 20  event_type_SetValue            24008 non-null  int64
 21  process_name_freq              24008 non-null  float64
 22  dest_port_category_dynamic     24008 non-null  int64
 23  dest_port_category_registered  24008 non-null  int64
 24  dest_port_category_well_known  24008 non-null  int64
 25  process_in_risky_dir           24008 non-null  int64
 26  file_in_risky_dir              24008 non-null  int64
 27  is_executable                  24008 non-null  int64
dtypes: bool(6), float64(2), int64(20)
memory usage: 4.2 MB

In [57]:
int((80/100)*len(df))

19206

In [59]:

X = df.copy()
model = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
df['anomaly_score'] = model.fit_predict(X)
df['isolation_score'] = model.decision_function(X)

In [61]:
df.to_csv('./data/isolated.csv')